---
- name: Setup my super awesome Dev environment
  hosts: localhost
  connection: local
  vars:
    ansible_become_password: '{{ lookup("env", "ANSIBLE_BECOME_PASSWORD") }}'
  vars_files:
    - ./vars.yml
- name: Include macos-playbook
  import_playbook: macos-playbook.yml
  when: ansible_distribution == 'Darwin'

- name: Include ubuntu-playbook
  import_playbook: ubuntu-playbook.yml
  when: ansible_distribution == 'Ubuntu'

- name: Include fedora-playbook
  import_playbook: fedora-playbook.yml
  when: ansible_distribution == 'Fedora'
