---
- name: Setup my super awesome Dev environment
  hosts: localhost
  connection: local
  vars:
    source_key: "./.ssh/id_ed25519"
    ssh_key_name: "id_ed25519"
    dest_key: "{{ lookup('env', 'HOME') }}/.ssh/{{ ssh_key_name }}"
    projects: "{{ lookup('env', 'HOME') }}/Documents/Projects"
    ssh_key: "{{ dest_key }}"

  pre_tasks:
    - import_tasks: tasks/fedora-setup.yml
    - import_tasks: tasks/ubuntu-setup.yml
  tasks:
    - import_tasks: tasks/ssh.yml
    - import_tasks: tasks/git-setup.yml
    - import_tasks: tasks/sdkman-setup.yml
    - import_tasks: tasks/awesome-java-setup.yml
    - import_tasks: tasks/js-setup.yml
    - import_tasks: tasks/personal-projects.yml
    # - import_tasks: tasks/debugger.yml
    - import_tasks: tasks/dotfiles.yml
    - import_tasks: tasks/flatpack.yml
    - import_tasks: tasks/snaps.yml
    - import_tasks: tasks/fonts.yml
