---
- name: Mac OS Dev environment setup
  hosts: localhost
  connection: local
  vars:
    ansible_become_password: '{{ lookup("env", "ANSIBLE_BECOME_PASSWORD") }}'
  vars_files:
    - ./vars.yml
  tasks:
    - name: Print hello world
      debug:
        msg: Hello world from Mac OS!!
