---
- name: Ubuntu Dev environment setup
  hosts: localhost
  connection: local
  vars:
    ansible_become_password: '{{ lookup("env", "ANSIBLE_BECOME_PASSWORD") }}'
  vars_files:
    - ./vars.yml
  
  tasks:
    - name: Set initial settings in Gnome Desktop
      import_tasks: tasks/gnome-pre-task.yml
      when: running_gnome == 'true'

    - name: Update Ubuntu packages
      become: yes
      apt:
        upgrade: "safe"
      when: ansible_distribution == 'Ubuntu'
      tags:
      - pkg
      - ubuntu

       
    - name: Install dependencies
      block:
      - name: Install build essentials
        become: true                          
        apt:                                  
          name:
          - patch 
          - rustc
          - libreadline6-dev 
          - libgmp-dev
          - libgdbm6
          - libdb-dev
          - uuid-dev
          - autoconf                        
          - bison                           
          - cmake                           
          - gir1.2-clutter-1.0              
          - gir1.2-gtop-2.0                 
          - gpg                             
          - imagemagick                     
          - libffi-dev                      
          - libgdbm-dev                     
          - libjemalloc2                    
          - libmagickwand-dev               
          - libmysqlclient-dev              
          - libncurses5-dev                 
          - libpq-dev                       
          - libpthread-stubs0-dev           
          - libreadline-dev                 
          - libreadline-dev                 
          - libsqlite3-0                    
          - libssl-dev                      
          - libvips                         
          - libyaml-dev                     
          - mupdf                           
          - mupdf-tools                     
          - pkg-config                      
          - postgresql-client               
          - postgresql-client-common        
          - redis-tools                     
          - sqlite3                         
          - wget                            
          - zlib1g-dev                      
          - build-essential
          - mercurial
          - binutils
          - gcc
        when: ansible_distribution == 'Ubuntu'
        tags:                                 
        - pkg
        - ubuntu                            
       
      - name: Core terminal tools
        become: true
        apt:                                  
          name:
          - alacritty
          - bat      
          - btop     
          - coreutils
          - curl                            
          - eza      
          - fd-find  
          - fzf      
          - gettext                         
          - git                             
          - jq                              
          - libtool                         
          - lsof     
          - make     
          - moreutils
          - optipng  
          - pango1.0-tools
          - plocate  
          - renameutils
          - ripgrep  
          - rsync    
          - sed      
          - sshpass  
          - stow                            
          - tldr     
          - tmux     
          - unzip                           
          - xclip    
          - zenity   
          - zoxide   
          - trash-cli
        tags:                                 
        - pkg
        - ubuntu                            
        when: ansible_distribution == 'Ubuntu'
    
    - name: Install Recommended Apps
      become: true
      apt:
        name:
        - flameshot # Better Screen shots
        - audacity
        - flatpak
        - fontforge
        - fontforge-common
        - fontforge-extras
        - gimp
        - hugin
        - peek
        - mypaint
        - vlc
        - xournalpp

    - import_tasks: tasks/nvidia-drivers.yml

    - import_tasks: tasks/bash.yml

    - import_tasks: tasks/java-environment.yml

    - import_tasks: tasks/ruby-environment.yml

    - import_tasks: tasks/nodejs-environment.yml

    - import_tasks: tasks/go-environment.yml

    - import_tasks: tasks/python-environment.yml

    - import_tasks: tasks/flatpack.yml

    - import_tasks: tasks/fonts.yml

    - import_tasks: tasks/gnome-improvement.yml

    - import_tasks: tasks/gnome-theme.yml

    - import_tasks: tasks/emacs-server.yml
    
    - import_tasks: tasks/gnome-post-tasks.yml
        
  handlers:
    - name: update apt cache
      apt:
        update_cache: yes
      become: yes          
