---
- name: Ubuntu Dev environment setup
  hosts: localhost
  connection: local
  vars:
    ansible_become_password: '{{ lookup("env", "ANSIBLE_BECOME_PASSWORD") }}'
  vars_files:
    - ./vars.yml
  
  tasks:
    - name: Set initial settings in Gnome Desktop
      import_tasks: tasks/gnome-pre-task.yml
      when: running_gnome == 'true'

    - name: Update Ubuntu packages
      become: true
      apt:
        upgrade: "safe"
      when: ansible_distribution == 'Ubuntu'
      tags:
        - pkg
        - ubuntu

       
    - name: Install dependencies
      block:
      - name: Install build essentials
        become: true                          
        apt:                                  
          name:                               
            - build-essential                 
            - cmake                           
            - pkg-config                      
            - libpthread-stubs0-dev
            - autoconf
            - gpg
            - wget
            - bison                   
            - libssl-dev              
            - libreadline-dev         
            - zlib1g-dev              
            - libyaml-dev             
            - libreadline-dev         
            - libncurses5-dev         
            - libffi-dev              
            - libgdbm-dev             
            - libjemalloc2            
            - libvips                 
            - imagemagick             
            - libmagickwand-dev       
            - mupdf                   
            - mupdf-tools             
            - gir1.2-gtop-2.0         
            - gir1.2-clutter-1.0      
            - redis-tools             
            - sqlite3                 
            - libsqlite3-0            
            - libmysqlclient-dev      
            - libpq-dev               
            - postgresql-client       
            - postgresql-client-common
        when: ansible_distribution == 'Ubuntu'
        tags:                                 
          - pkg
          - ubuntu                            
       
      - name: Core terminal tools
        become: true
        apt:                                  
          name:
            - trash-cli
            - fzf
            - ripgrep
            - bat
            - eza
            - zoxide
            - plocate
            - btop
            - fd-find
            - tldr
            - curl                            
            - git                             
            - unzip                           
            - libtool                         
            - gettext                         
            - jq                              
            - stow                            
            - tmux
            - lsof
            - moreutils
            - alacritty
            - renameutils
            - coreutils
            - rsync
            - zenity
            - optipng
            - sed
            - awk
            - make
            - sshpass
            - pango1.0-tools
            - xclip
        tags:                                 
          - pkg
          - ubuntu                            
        when: ansible_distribution == 'Ubuntu'

    - name: Install Nvidia drivers
      become: true
      shell:
        cmd: ubuntu-drivers install

    - name: Installing extra video tools
      become: true
      apt:
       name:
       - nvidia-vaapi-driver
       - vdpauinfo

    - name: Install Recommended Apps
      become: true
      apt:
        name:
        - mypaint
        - hugin
        - peek
        - audacity
        - fontforge
        - fontforge-common
        - fontforge-extras
        - vulkan-tools
        - flatpak
        - gimp

    - import_tasks: tasks/bash.yml

    - import_tasks: tasks/java-environment.yml

    - import_tasks: tasks/programming-environments.yml
    
    - import_tasks: tasks/flatpack.yml

    - import_tasks: tasks/gnome-post-tasks.yml
        
  handlers:
    - name: update apt cache
      apt:
        update_cache: yes
      become: yes          
