- name: Setup Basics for ALL tasks in this Ansible setup.
  dnf:
    name:
      - git
      - curl
    state: latest
    become: yes

- name: Setup Ansible Galaxy dependencies
  shell: if type poetry &> /dev/null; then poetry install --no-root; else pip3 install -r .config/assets/requirements.txt; fi ansible-galaxy install -r requirements.yml
  become: no
