- name: Check if Staship is installed
  stat:
    path: "/usr/local/bin/starship"
  register: starship
  become: no

- name: Install Starship shell promtp
  become: true
  shell:
    cmd: curl -sS https://starship.rs/install.sh | sh -s -- -y
  when: not starship.stat.exists
