- name: Cloning .dotfiles
  ansible.builtin.git:
    repo: 'git@github.com:juankprada/dotfiles.git'
    dest: "{{ projects }}/dotfiles"
    recursive: yes
    update: yes
    accept_hostkey: yes
    version: main
  tags:
    - install
    - dotfiles
    - stow
  become: no

- name: Stow dotfiles
  shell: cd {{ projects }}/dotfiles && chmod +x install &&  ./install
  tags:
    - install
    - dotfiles
    - stow
  become: no
