- name: Cloning .dotfiles
  git:
    clone: yes
    repo: 'git@github.com:juankprada/dotfiles.git'
    dest: "{{ projects }}/dotfiles"
    update: yes
    accept_hostkey: yes
    version: main
    key_file: "{{ lookup('env', 'HOME') }}/.ssh/{{ssh_key_name}}"
  tags:
    - install
    - dotfiles
    - stow
  become: no

- name: Stow dotfiles
  shell: cd {{ projects }}/dotfiles && chmod +x install &&  ./install
  tags:
    - install
    - dotfiles
    - stow
  become: no
