- name: Update Fedora
  dnf:
    name: '*'
    state: latest
    update_cache: yes
    update_only: yes
  become: yes

- name: Enable the RPM Fusion Free repository
  dnf:
    name: "https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ansible_distribution_major_version}}.noarch.rpm"
    state: present
  become: yes
  when: ansible_distribution == 'Fedora'

- name: Enable the RPM Fusion Non-Free repository
  dnf:
    name: "https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ansible_distribution_major_version}}.noarch.rpm"
    state: present
  become: yes
  when: ansible_distribution == 'Fedora'

- name: Remove unneded packages
  dnf:
    autoremove: yes
  become: yes
  when: ansible_distribution == 'Fedora'

- name: Install System Packages 1 core development tools on Red Hat based Distros
  become: true
  dnf:
    name:
      - '@Development Tools'
      - '@Development Libraries'
    state: latest
  tags:
    - install
    - core
  when:  ansible_distribution  == 'Fedora' or  ansible_distribution  == 'CentOs' or  ansible_distribution  == 'RedHat'


- name: Install System Packages 2 (zsh, emacs, curl, git, lua, unzip, libtool, libtool, gettext)
  become: true
  dnf:
    name:
      - zsh
      - emacs
      - curl
      - git
      - lua
      - unzip
      - libtool
      - gettext
      - jq
    state: latest
  tags:
    - install
    - core
  when:  ansible_distribution  == 'Fedora' or  ansible_distribution  == 'CentOs' or  ansible_distribution  == 'RedHat'

- name: Install System Packages 3 (the rest)
  become: true
  dnf:
    name:
      - btop
      - golang
      - lsof
      - i3
      - ccache
      - ninja-build
      - python3-pip
      - nvidia-settings
      - pavucontrol
      - moreutils
      - snapd
    state: latest
  tags:
    - install
    - core
  when:  ansible_distribution  == 'Fedora' or  ansible_distribution  == 'CentOs' or  ansible_distribution  == 'RedHat'

- name: Install Clang
  become: true
  dnf:
    name:
      - clang
      - clang-10-libs
      - clang-11-libs
      - clang-12-libs
      - clang-13-libs
      - clang-14-libs
      - clang-15-libs
      - clang
    state: latest
  tags:
    - install
    - core
  when:  ansible_distribution  == 'Fedora' or  ansible_distribution  == 'CentOs' or  ansible_distribution  == 'RedHat'

- name: Install Art studio
  become: true
  dnf:
    name:
      - blender
      - gimp
      - inkscape
      - scribus
    state: latest
  tags:
    - install
    - core
  when:  ansible_distribution  == 'Fedora' or  ansible_distribution  == 'CentOs' or  ansible_distribution  == 'RedHat'

- name: Enable Classic SNAPs support
  shell: ln -s /var/lib/snapd/snap /snap
  become: yes
  when:  ansible_distribution  == 'Fedora' or  ansible_distribution  == 'CentOs' or  ansible_distribution  == 'RedHat'
