- name: Update Fedora
  dnf:
    name: '*'
    state: latest
    update_cache: yes
    update_only: yes
  become: yes
  when:  ansible_distribution  == 'Fedora' or  ansible_distribution  == 'CentOs' or  ansible_distribution  == 'RedHat'
  tags:
    - setup


- name: Enable the RPM Fusion Free repository
  dnf:
    name: "https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ansible_distribution_major_version}}.noarch.rpm"
    state: present
    disable_gpg_check: True
  become: yes
  when:  ansible_distribution  == 'Fedora' or  ansible_distribution  == 'CentOs' or  ansible_distribution  == 'RedHat'
  tags:
    - setup


- name: Enable the RPM Fusion Non-Free repository
  dnf:
    name: "https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ansible_distribution_major_version}}.noarch.rpm"
    state: present
    disable_gpg_check: True
  become: yes
  when:  ansible_distribution  == 'Fedora' or  ansible_distribution  == 'CentOs' or  ansible_distribution  == 'RedHat'
  tags:
    - setup


- name: Remove unneded packages
  dnf:
    autoremove: yes
  become: yes
  when:  ansible_distribution  == 'Fedora' or  ansible_distribution  == 'CentOs' or  ansible_distribution  == 'RedHat'
  tags:
    - setup


- name: Install System Packages 1 core development tools on Red Hat based Distros
  become: true
  dnf:
    name:
      - '@Development Tools'
      - '@Development Libraries'
      - gtk2-devel
    state: latest
  tags:
    - setup
    - install
    - core
  when:  ansible_distribution  == 'Fedora' or  ansible_distribution  == 'CentOs' or  ansible_distribution  == 'RedHat'


- name: Install Xmonad and tools for my Desktop Environment
  become: true
  dnf:
    name:
      - sddm
      - xmonad
      - xrdb
      - xset
      - xsettingsd
      - xdotool
      - xmobar
      - alacritty
      - dmenu
      - slock
      - light
      - nitrogen
      - lxappearance
      - xscreensaver
      - xfce4-power-manager
      - picom
      - arandr
      - autorandr
      - pavucontrol
      - volumeicon
      - shutter
      - dunst # notifications
      - blueman
      - xorg-x11-xinit-session
      - lxappearance
      - rofi
      - unclutter-xfixes #unclutter
      - jgmenu
      - arc-theme
      - papirus-icon-theme
  when:  ansible_distribution  == 'Fedora' or  ansible_distribution  == 'CentOs' or  ansible_distribution  == 'RedHat'

- name: Install System Packages 2 (zsh, emacs, curl, git, lua, unzip, libtool, libtool, gettext)
  become: true
  dnf:
    name:
      - emacs
      - curl
      - git
      - lua
      - unzip
      - libtool
      - gettext
      - jq
      - stow
      - tmux
      - qalculate-gtk
      - flatpak
    state: latest
  tags:
    - setup
    - install
    - core
  when:  ansible_distribution  == 'Fedora' or  ansible_distribution  == 'CentOs' or  ansible_distribution  == 'RedHat'

- name: Install System Packages 3 (the rest)
  become: true
  dnf:
    name:
      - btop
      - golang
      - lsof
      - i3
      - ccache
      - ninja-build
      - python3-pip
      - nvidia-settings
      - moreutils
      - snapd
    state: latest
  tags:
    - setup
    - install
    - core
  when:  ansible_distribution  == 'Fedora' or  ansible_distribution  == 'CentOs' or  ansible_distribution  == 'RedHat'

- name: Install Clang
  become: true
  dnf:
    name:
      - clang
    state: latest
  tags:
    - stup
    - install
    - core
  when:  ansible_distribution  == 'Fedora' or  ansible_distribution  == 'CentOs' or  ansible_distribution  == 'RedHat'

- name: Install Art studio
  become: true
  dnf:
    name:
      - blender
      - gimp
      - inkscape
      - scribus
    state: latest
  tags:
    - install
    - core
    - art
  when:  ansible_distribution  == 'Fedora' or  ansible_distribution  == 'CentOs' or  ansible_distribution  == 'RedHat'


## TODO
## There are things here that may be needed.

# * lxsession (polkit) - authentication agents | We may not need it as Fedora i3 may have one setup




# * voluemicon (pavucontrol??)

# * emacs daemon
# * clipboard manager
# * urxvt/xterm ?
# * music plaer cmus/mp3blaster
# * irc client
# * File Manger (PCManFM/Krusader/Find other/Thunar)
# * LXAppearance
# * Scrot for PrintScreen
# *  WMDOCKER Window Maker docker?
