- name: Update Fedora
  dnf:
    name: '*'
    state: latest
    update_cache: yes
    update_only: yes
  become: yes
  when:  ansible_distribution  == 'Fedora' or  ansible_distribution  == 'CentOs' or  ansible_distribution  == 'RedHat'
  tags:
    - setup


- name: Enable the RPM Fusion Free repository
  dnf:
    name: "https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ansible_distribution_major_version}}.noarch.rpm"
    state: present
    disable_gpg_check: True
  become: yes
  when:  ansible_distribution  == 'Fedora' or  ansible_distribution  == 'CentOs' or  ansible_distribution  == 'RedHat'
  tags:
    - setup


- name: Enable the RPM Fusion Non-Free repository
  dnf:
    name: "https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ansible_distribution_major_version}}.noarch.rpm"
    state: present
    disable_gpg_check: True
  become: yes
  when:  ansible_distribution  == 'Fedora' or  ansible_distribution  == 'CentOs' or  ansible_distribution  == 'RedHat'
  tags:
    - setup


- name: Remove unneded packages
  dnf:
    autoremove: yes
  become: yes
  when:  ansible_distribution  == 'Fedora' or  ansible_distribution  == 'CentOs' or  ansible_distribution  == 'RedHat'
  tags:
    - setup


- name: Install System Packages 1 core development tools on Red Hat based Distros
  become: true
  dnf:
    name:
      - '@Development Tools'
      - '@Development Libraries'
      - '@Sound and Video'
      - '@Multimedia'
      - gtk2-devel
    state: latest
    allowerasing: true
  tags:
    - setup
    - install
    - core
  when:  ansible_distribution  == 'Fedora' or  ansible_distribution  == 'CentOs' or  ansible_distribution  == 'RedHat'

- name: Swapp ffmpeg packages
  become: true
  shell: |
    dnf swap ffmpeg-free ffmpeg --allowerasing
  when:  ansible_distribution  == 'Fedora' or  ansible_distribution  == 'CentOs' or  ansible_distribution  == 'RedHat'

- name: Install System Packages (zsh, emacs, curl, git, lua, unzip, libtool, gettext)
  become: true
  dnf:
    name:
      - trash-cli
      - emacs
      - bat
      - curl
      - git
      - lua
      - unzip
      - libtool
      - gettext
      - jq
      - stow
      - tmux
      - flatpak
      - python3-websocket-client
    state: latest
  tags:
    - setup
    - install
    - core
  when:  ansible_distribution  == 'Fedora' or  ansible_distribution  == 'CentOs' or  ansible_distribution  == 'RedHat'

- name: Install System Packages 2 (the rest)
  become: true
  dnf:
    name:
      - mozc
      - renameutils
      - alacritty
      - btop
      - golang
      - lsof
      - ccache
      - python3-pip
      - moreutils
      - rpmfusion-free-release-tainted
      - rpmfusion-nonfree-release-tainted
      - dnfdragora
      - eza
      - bat
      - kcm_wacomtablet
      - krename
    state: latest
  tags:
    - setup
    - install
    - core
  when:  ansible_distribution  == 'Fedora' or  ansible_distribution  == 'CentOs' or  ansible_distribution  == 'RedHat'

- name: Install Nvidia Packages
  become: true
  dnf:
    name:
      - akmod-nvidia
      - xorg-x11-drv-nvidia-cuda
      - nvidia-vaapi-driver
      - nvidia-settings
      - xorg-x11-drv-nvidia-power
      - vulkan
      - vulkan-tools
      - xorg-x11-drv-nvidia-cuda-libs
      - nvidia-vaapi-driver
      - libva-utils
      - vdpauinfo
  tags:
    - setup
    - install
    - core
  when:  ansible_distribution  == 'Fedora' or  ansible_distribution  == 'CentOs' or  ansible_distribution  == 'RedHat'

- name: Install Clang
  become: true
  dnf:
    name:
      - clang
    state: latest
  tags:
    - stup
    - install
    - core
  when:  ansible_distribution  == 'Fedora' or  ansible_distribution  == 'CentOs' or  ansible_distribution  == 'RedHat'

- name: Install Art studio
  become: true
  dnf:
    name:
      - blender
      - gimp
      - inkscape
      - scribus
      - ImageMagick
      - python3
      - jq
      - git
      - zip
      - coreutils
      - wget
      - rsync
      - libnotify
      - parallel
      - optipng
      - lftp
      - zenity
      - sed
      - make
      - python3-pip
      - python3-unidecode
      - python-is-python3
      - ghostscript
      - sshpass
      - pango
      - xclip
      - mypaint
      - hugin
      - peek
      - audacity
      - fontforge
    state: latest
  tags:
    - install
    - core
    - art
    - 0ad
  when:  ansible_distribution  == 'Fedora' or  ansible_distribution  == 'CentOs' or  ansible_distribution  == 'RedHat'


- name: Install Games
  become: true
  dnf:
    name:
      - steam
      - wesnoth
  tags:
    - install
    - core
    - art
    - 0ad
  when:  ansible_distribution  == 'Fedora' or  ansible_distribution  == 'CentOs' or  ansible_distribution  == 'RedHat'

# - name: Public KMOD key exists?
#   stat:
#     path: "/etc/pki/akmods/certs/public_key.der"
#   register: kmodkey
#   tags:
#     - install
#     - core
#   become: yes
#   when:  ansible_distribution == 'Fedora' or  ansible_distribution  == 'CentOs' or  ansible_distribution  == 'RedHat'

# - name: Self generate key and certificate for Secure Boot
#   become: true
#   shell: |
#     /usr/sbin/kmodgenca
#   when: kmodkey.stat.exists == False

# - name: Importing Secure Boot key
#   become: true
#   expect:
#     command: mokutil --import /etc/pki/akmods/certs/public_key.der
#     responses:
#       Question:
#         - lookup("env", "ANSIBLE_BECOME_PASSWORD")
#         - lookup("env", "ANSIBLE_BECOME_PASSWORD")
#   when: when: kmodkey.stat.exists == False

- name: Enable Nvidia Suspend scripts
  systemd:
    name: nvidia-suspend
    enabled: true
  become: yes
  tags:
    - install
    - core
    - art
    - 0ad
  when:  ansible_distribution  == 'Fedora' or  ansible_distribution  == 'CentOs' or  ansible_distribution  == 'RedHat'


- name: enable Nvidia Resume scripts
  systemd:
    name: nvidia-resume
    enabled: true
  become: yes
  tags:
    - install
    - core
    - art
    - 0ad
  when:  ansible_distribution  == 'Fedora' or  ansible_distribution  == 'CentOs' or  ansible_distribution  == 'RedHat'

- name: enable Nvidia Hibernate Scripts
  systemd:
    name: nvidia-hibernate
    enabled: true
  become: yes
  tags:
    - install
    - core
    - art
    - 0ad
  when:  ansible_distribution  == 'Fedora' or  ansible_distribution  == 'CentOs' or  ansible_distribution  == 'RedHat'

- name: Fix Numphy  setup correctly on modprobe
  shell: |
    grep -qxF 'options hid_apple fnmode=0' /etc/modprobe.d/hid_apple.conf || echo 'options hid_apple fnmode=0' >> /etc/modprobe.d/hid_apple.conf
  tags:
    - install
    - core
  become: yes
  when:  ansible_distribution == 'Fedora' or ansible_distribution == 'CentOs' or  ansible_distribution  == 'RedHat'

- name: Check if Numphy is setup correctly on dracut
  stat:
    path: "/etc/dracut.conf.d/hid_apple.conf"
  register: numphy
  tags:
    - install
    - core
  become: yes
  when:  ansible_distribution == 'Fedora' or ansible_distribution == 'CentOs' or  ansible_distribution  == 'RedHat'

- name: Fix Numphy keyboard on Fedora
  become: true
  shell: |
    echo "install_items+=/etc/modprobe.d/hid_apple.conf" >> /etc/dracut.conf.d/hid_apple.conf && dracut --force
  when: ansible_distribution == 'Fedora' or ansible_distribution == 'CentOs' or ansible_distribution  == 'RedHat' and numphy.stat.exists == False


- name: Install the build dependencies for Krita
  command:
    dnf builddep -y krita
  args:
    warn: false
  register: dnf_result
  become: yes
  when: ansible_pkg_mgr == 'dnf' and ansible_distribution == 'Fedora' or ansible_distribution == 'CentOs' or ansible_distribution  == 'RedHat'
  changed_when: '"Nothing to do" not in dnf_result.stdout'
