
- name: Add the flathub flatpak repository remote to the user installation
  community.general.flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
    method: user
  tags:
    - setup


- name: Install multiple packages
  community.general.flatpak:
    name:
      - org.beeref.BeeRef
      - io.beekeeperstudio.Studio
      - com.brave.Browser
      - sh.cider.Cider
      - com.discordapp.Discord
      - net.cozic.joplin_desktop
      - org.gnome.World.PikaBackup
      - com.skype.Client
      - com.slack.Slack
      - us.zoom.Zoom
      - org.inkscape.Inkscape
      - org.kde.kdenlive
      - com.obsproject.Studio
      - org.blender.Blender
      - org.gnome.gitlab.YaLTeR.VideoTrimmer
      - org.gnome.gitlab.YaLTeR.Identity
      - com.neatdecisions.Detwinner

    state: present
    method: user
  tags:
    - install
    - flatpak

- name: Install DisplayCal in opensuse
  community.general.flatpak:
    name:
      - net.displaycal.DisplayCAL
    state: present
    method: user
  when: ansible_distribution == 'openSUSE Leap'


- name: Install Extra games
  community.general.flatpak:
    name:
      - org.citra_emu.citra
      - com.heroicgameslauncher.hgl
      - com.snes9x.Snes9x
      - dev.goats.xivlauncher
      - com.shatteredpixel.shatteredpixeldungeon
      - net.openra.OpenRA
      - com.frogatto.Frogatto

    state: present
    method: user
  tags:
    - install
    - flatpak
