- name: Git personal setup email
  git_config:
    name: user.email
    scope: global
    value: "juankprada@gmail.com"
  tags:
  - git-personal
- name: Git personal setup name
  git_config:
    name: user.name
    scope: global
    value: "Juank Prada"
  tags:
  - git-personal
