- name: Installing Java Development Enviornment
  include_role:                   
    name: Comcast.sdkman          
  vars:                           
    sdkman_install_packages:      
      - { candidate: java, version: 22.0.2-tem }
      - { candidate: java, version: 22.0.2-graalce }
      - { candidate: quarkus }    
      - { candidate: ant }        
      - { candidate: maven }      
      - { candidate: gradle }     
      - { candidate: jbang }      
      - { candidate: jbake }      
    sdkman_defaults:              
      java: 22.0.2-tem            
    sdkman_update_alternatives:   
      - candidate: java           
        name: java                
        link: /usr/bin/java       
      - candidate: java           
        name: javac               
        link: /usr/bin/javac      
  when: install_java_env == 'true'
