- name: Install NodeJS Development environment in Linux
  become: no
  block:
  - name: Check if Nvm is installed
    stat:
      path: "{{ ansible_env.HOME }}/.nvm/nvm.sh"
    register: nvm_installed

  - name: Install nvm
    ansible.builtin.shell: >
      curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.1/install.sh | bash
    args:
      creates: "{{ ansible_env.HOME }}/.nvm/nvm.sh"
    when: nvm_installed.stat.exists == False

  - name: Install Node LTS
    shell: "source {{ ansible_env.HOME }}/.nvm/nvm.sh && nvm install --lts"
    args:
      executable: /bin/bash

  when: install_nodejs_env == 'true' and (ansible_distribution == 'Ubuntu' or ansible_distribution == 'Fedora')
