- name: Install Nvidia drivers and tools in Ubuntu
  block:
  - name: Install Nvidia drivers
    become: true
    shell:
      cmd: ubuntu-drivers install

  - name: Installing extra video tools
    become: true
    apt:
      name:
      - nvidia-vaapi-driver
      - vdpauinfo
      - vulkan-tools
  when: ansible_distribution == 'Ubuntu'
  tags:
  - drivers
  - ubuntu

- name: Install Nvidia drivers and tools under OpenSuse Leap
  block:
  - name: Install Drivers (OpenSuse Leap)
    become: true
    zypper:
      name:
        - nvidia-video-G06
        - nvidia-gl-G06
      state: latest
      disable_recommends: false
    tags:
      - install
      - core
      - art
    when:  ansible_distribution  == 'openSUSE Leap'

- name: Install Nvidia drivers and tools under Debian
  block:
  - name: Install drivers
    become: true
    apt:
      name:
      - nvidia-driver
      - firmware-misc-nonfree
      - vdpauinfo
      - vulkan-tools
      - libnvoptix1
      - mesa-vulkan-drivers
  - name: update apt cache
    apt:
      update_cache: yes
    become: yes
  - name: Install drivers
    become: true
    apt:
      name:
      - nvidia-driver-libs:i386
      - libglx-mesa0:i386
      - mesa-vulkan-drivers:i386
      - libgl1-mesa-dri:i386
  when: ansible_distribution == 'Debian' and 0 > 1
  tags:
  - drivers
  - debian

- name: Install Nvidia drivers and tools under Fedora
  block:
  - name: Install Nvidia Packages
    become: true
    dnf:
      name:
        - akmod-nvidia
        - xorg-x11-drv-nvidia-cuda
        - nvidia-vaapi-driver
        - nvidia-settings
        - xorg-x11-drv-nvidia-power
        - vulkan
        - vulkan-tools
        - xorg-x11-drv-nvidia-cuda-libs
        - nvidia-vaapi-driver
        - libva-utils
        - vdpauinfo
    
  - name: Enable Nvidia Suspend scripts
    systemd:
      name: nvidia-suspend
      enabled: true
    become: yes
      
  - name: enable Nvidia Resume scripts                                                                                  
    systemd:                                                                                                            
      name: nvidia-resume                                                                                               
      enabled: true                                                                                                     
    become: yes                                                                                                         
      
  - name: enable Nvidia Hibernate Scripts                                                                               
    systemd:                                                                                                            
      name: nvidia-hibernate                                                                                            
      enabled: true                                                                                                     
    become: yes                                                                                                         
  when:  ansible_distribution  == 'Fedora' or  ansible_distribution  == 'CentOs' or  ansible_distribution  == 'RedHat'
  tags:
  - drivers
  - fedora
