- name: Clone Trayer repository
  git:
    clone: yes
    repo: 'https://github.com/sargon/trayer-srg.git'
    dest: "{{ projects}}/trayer"
  tags:
    - setup
  become: no

- name: Build Trayer
  shell: cd {{ projects }}/trayer && ./configure && make
  tags:
    - setup

- name: Install Trayer
  shell: cd {{ projects }}/trayer && make install
  become: yes


- name: disable Lightdm
  systemd:
    name: lightdm
    enabled: false
  become: yes

- name: enable SDDM
  systemd:
    name: sddm
    enabled: true
  become: yes


- name: Clone System Sounds repository
  git:
    clone: yes
    repo: 'https://gitlab.com/juankprada/dtos-sounds.git'
    dest: "{{ projects }}/dtos-sounds"
  tags:
    - setup
  become: no


- name: Determine if /opt/system-sounds exists
  stat:
    path: "{{system_sounds_path}}"
  register: os_sounds_path

- name: Create path
  file:
    path: "{{system_sounds_path}}"
    owner: "{{ lookup('env', 'USER') }}"
    group: "{{ lookup('env', 'USER') }}"
    mode: 0775
    state: directory
  become: yes
  when: not os_sounds_path.stat.exists


- name: Copy System Sounds to OPT directory
  copy:
    src: "{{ projects }}/dtos-sounds/"
    dest: "{{ system_sounds_path }}"
    force: yes
  when: os_sounds_path.stat.exists
