- name: Install Mise                                                                
  become: yes                                                                       
  block:                                                                            
  - name: Create /etc/apt/keyrings directory                                        
    file:                                                                           
      path: /etc/apt/keyrings                                                       
      state: directory                                                              
      mode: '0755'                                                                  
                                                                                    
  - name: Download mise gpg keys                                                    
    ansible.builtin.get_url:                                                        
      url: https://mise.jdx.dev/gpg-key.pub                                         
      dest: /tmp/mise-gpg-key.pub                                                   
    notify: update apt cache                                                        
                                                                                    
  - name: Import GPG Key                                                            
    shell:                                                                          
      cmd: gpg --dearmor < /tmp/mise-gpg-key.pub | sudo tee /etc/apt/keyrings/mise-archive-keyring.gpg > /dev/null
                                                                                    
  - name: Add MISE repository to sources.list.d                                     
    template:                                                                       
      src: templates/mise.list.j2                                                   
      dest: /etc/apt/sources.list.d/mise.list                                       
      mode: '0644'                                                                  
    notify: update apt cache                                                        
                                                                                    
  - name: Make sure the file is owned by root and permissions are correct           
    file:                                                                           
      path: /etc/apt/sources.list.d/mise.list                                       
      state: touch                                                                  
      owner: root                                                                   
      group: root                                                                   
      mode: '0644'                                                                  
                                                                                    
  - name: update apt cache                                                          
    apt:                                                                            
      update_cache: yes                                                             
                                                                                    
  - name: Install MISE package                                                      
    apt:                                                                            
      name: mise                                                                    
      state: present                                                                
                                                                                    
                                                                                    
- name: Install Ruby Development environment                                        
  become: no                                                                        
  block:                                                                            
  - name: Install Ruby Language - Latest version                                    
    shell:                                                                          
      cmd: mise use --global ruby@latest                                            
  - name: Installing Ruby on Rails                                                  
    shell:                                                                          
      cmd: mise x ruby -- gem install rails --no-document                           
  when: install_ruby_env == 'true'                                                  
                                                                                    
                                                                                    
- name: Install Node.js development environment                                     
  become: no                                                                        
  shell:                                                                            
    cmd: mise use --global node@latest                                              
  when: install_nodejs_env == 'true'                                                
                                                                                    
                                                                                    
- name: Install Go development environment                                          
  become: no                                                                        
  shell:                                                                            
    cmd: mise use --global go@latest                                                
  when: install_nodejs_env == 'true'                                                
                                                                                    
- name: Install Python dev environment                                              
  become: no                                                                        
  block:                                                                            
  - name: Install latest python version                                             
    shell:                                                                          
      cmd: mise use --global python@latest                                          
  - name: Install Pip                                                               
    shell:                                                                          
      cmd: python -m ensurepip --upgrade                                            
  - name: Installing Pipenv                                                         
    shell:                                                                          
      cmd: pip3 install --user pipenv                                               
  when: install_python_env == 'true'                                                
                                                                                    
- name: install Elixir development environment                                      
  become: no                                                                        
  block:                                                                            
  - name: Install Erlang                                                            
    shell:                                                                          
      cmd: mise use --global erlang@latest                                          
  - name: Install Elixir                                                            
    shell:                                                                          
      cmd: mise use --global elixir@latest && mise x elixir -- mix local.hex --force
