- name: Install Node.js development environment                                     
  become: no                                                                        
  shell:                                                                            
    cmd: mise use --global node@latest                                              
  when: install_nodejs_env == 'true'                                                
                                                                                    
- name: Install Go development environment                                          
  become: no                                                                        
  shell:                                                                            
    cmd: mise use --global go@latest                                                
  when: install_nodejs_env == 'true'                                                
                                                                                    
- name: Install Python dev environment                                              
  become: no                                                                        
  block:                                                                            
  - name: Install latest python version                                             
    shell:                                                                          
      cmd: mise use --global python@latest                                          
  - name: Install Pip                                                               
    shell:                                                                          
      cmd: python -m ensurepip --upgrade                                            
  - name: Installing Pipenv                                                         
    shell:                                                                          
      cmd: pip3 install --user pipenv                                               
  when: install_python_env == 'true'                                                
                                                                                    
- name: install Elixir development environment                                      
  become: no                                                                        
  block:                                                                            
  - name: Install Erlang                                                            
    shell:                                                                          
      cmd: mise use --global erlang@latest                                          
  - name: Install Elixir                                                            
    shell:                                                                          
      cmd: mise use --global elixir@latest && mise x elixir -- mix local.hex --force
