- name: Install Ruby Development environment in Ubuntu
  become: no
  block:
  - name: Check if Rbenv is installed
    stat:
      path: "~/.rbenv/bin/rbenv"
    register: rbenv_installed

  - name: Install Rbenv in Ubuntu
    ansible.builtin.git:
      repo: "https://github.com/rbenv/rbenv.git"
      dest: "~/.rbenv"
    when: rbenv_installed.stat.exists == False

  - name: Configure Rbenv
    shell: ~/.rbenv/bin/rbenv init > /dev/null
    args:
      executable: /bin/bash

  - name: Create plugins directory for rbenv
    file:
      path:  ~/.rbenv/plugins/
      state: directory

  - name: Installing Rbenv Install Plugin
    ansible.builtin.git:
      repo: "https://github.com/rbenv/ruby-build.git"
      dest: "~/.rbenv/plugins/ruby-build"

  - name: Installing Ruby
    shell: eval "$(~/.rbenv/bin/rbenv init - --no-rehash bash)" && rbenv install 3.3.4
    args:
      executable: /bin/bash

  when: install_ruby_env == 'true' and ansible_distribution == 'Ubuntu'


- name: Install Ruby Development environment in Fedora
  block:
  - name: Install rbenv
    dnf:
      name:
      - rbenv
      state: latest
    become: yes

  - name: Configure Rbenv
    shell: rbenv init
    args:
      executable: /bin/bash
  - name: Installing Ruby
    shell: rbenv install 3.3.4
    args:
      executable: /bin/bash
  when: install_ruby_env == 'true' and ansible_distribution == 'Fedora'
