- name: Check if sdkman is installed
  shell: test -d {{ ansible_env.HOME }}/.sdkman && echo "yes" || echo "no"
  register: is_sdkman_installed
  tags:
    - setup

- name: Install SDKMan Package Manager
  shell: curl -s "https://get.sdkman.io" | bash
  when : is_sdkman_installed.stdout == "no"
  tags:
    - setup


- name: Ensure presense of .zshrc file
  file: state=touch path={{ ansible_env.HOME }}/.zshrc
  tags:
    - setup
