- name: Ensure .ssh directory exists.
  file:
    dest: "{{ dest_key | dirname }}"
    mode: 0700
    state: directory
  tags:
    - dotfiles
    - install
    - ssh
  become: no

- name: Install ssh key
  copy:
    src: "{{ source_key }}"
    dest: "{{ dest_key }}"
    mode: 0600
  tags:
    - dotfiles
    - install
    - ssh
  become: no

- name: Install ssh key public
  copy:
    src: "{{ source_key }}.pub"
    dest: "{{ dest_key }}.pub"
    mode: 0644
  tags:
    - dotfiles
    - install
    - ssh
  become: no

- name: Set authorized key took from file
  authorized_key:
    user: "{{ lookup('env', 'USER') }}"
    state: present

    key: "{{ lookup('file', '~/.ssh/id_ed25519.pub') }}"
  with_fileglob:
  - "{{ lookup('env', 'HOME') }}/.ssh/*.pub"
  tags:
    - dotfiles
    - ssh
    - install
  become: no

- name: Add key to SSH Agent
  shell: "ssh -o ForwardAgent=no {{inventory_hostname}} 'eval `ssh-agent -s` && ssh-add $HOME/.ssh/id_ed25519 && ssh-add -l'"
  #script: ./setup.sh
  tags:
    - dotfiles
    - ssh
    - install
  become: no
