- name: Update Ubuntu packages
  become: true
  apt:
    upgrade: "safe"
  when: ansible_distribution == 'Ubuntu'
  tags:
    - pkg
    - ubuntu

- name: Install dependencies
  block:
  - name: Install build essentials
    become: true                          
    apt:                                  
      name:                               
        - build-essential                 
        - cmake                           
        - pkg-config                      
        - libpthread-stubs0-dev
        - autoconf                
        - bison                   
        - clang                   
        - rustc                   
        - libssl-dev              
        - libreadline-dev         
        - zlib1g-dev              
        - libyaml-dev             
        - libreadline-dev         
        - libncurses5-dev         
        - libffi-dev              
        - libgdbm-dev             
        - libjemalloc2            
        - libvips                 
        - imagemagick             
        - libmagickwand-dev       
        - mupdf                   
        - mupdf-tools             
        - gir1.2-gtop-2.0         
        - gir1.2-clutter-1.0      
        - redis-tools             
        - sqlite3                 
        - libsqlite3-0            
        - libmysqlclient-dev      
        - libpq-dev               
        - postgresql-client       
        - postgresql-client-common
    when: ansible_distribution == 'Ubuntu'
    tags:                                 
      - pkg
      - ubuntu                            

  - name: Core terminal tools
    become: true
    apt:                                  
      name:                               
        - fzf
        - ripgrep
        - bat
        - eza
        - zoxide
        - plocate
        - btop
        - fd-find
        - tldr
        - curl                            
        - git                             
        - unzip                           
        - libtool                         
        - gettext                         
        - jq                              
        - stow                            
        - tmux
        - lsof
        - moreutils
    tags:                                 
      - pkg
      - ubuntu                            
    when: ansible_distribution == 'Ubuntu'
