---
- host: localhost
  tasks:
   - debug:
       msg: play1
       
- name: Linux Setup Playbook
  hosts: localhost
  connection: local
  vars:
    ansible_become_password: '{{ lookup("env", "ANSIBLE_BECOME_PASSWORD") }}'
  vars_files:
   - ../vars.yml
     
   
       
